name: Run prettier write

on:
  pull_request:

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Check out PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr checkout ${{ github.event.pull_request.number }}
      - uses: actions/cache@v2
        name: Configure npm caching
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/workflows/prettier.yml') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - name: Run prettier
        run: |-
          npx prettier --write '_data/*/*.json'
      - name: Set name
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git config user.name "ligi"
      - name: Set email
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git config user.email "ligi@ligi.de"
      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git commit -a -m 'Fix formatting'
      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git commit -a -m 'Fix formatting'

